baseURL: "https://jfermat.github.io/"
languageCode: "es"
defaultContentLanguage: "es"
title: "Jordi Ferré"

theme: "LoveIt"

author:
  name: "Jordi Ferré"

params:
  author: "Jordi Ferré"
  description: "Mi sitio Geek 🤓"
  version: "0.2.X"
  dateformat: 02-01-2006
  images: ["/logo.png"]
  header:
    title:
      logo: "https://avatars3.githubusercontent.com/u/33716069"
      name: "Jordi Ferré"
  footer:
    copyright: false
    author: true
    license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  home:
    profile:
      enable: true
      avatarURL: https://avatars3.githubusercontent.com/u/33716069
      title: Jordi Ferré Matamoros
      subtitle: "Mi sitio Geek 🤓"
      social: true
      typeit: true
  social:
    github: jfermat
    linkedin: jordiferre
    Instagram: xordeee
    Telegram: xordeee
    Gitlab: jferre
    Strava: 59046961
    Email: "jordiferre@gmail.com"
  analytics:
    enable: true
    google:
      id: "G-GR0HB6SQQD"
      anonymizeIP: false
  cookieconsent:
    enable: true
  page:
    comment:
      enable: false
      
menu:
  main:
    - identifier: "Inico"
      name: "Inicio"
      url: "/"
      title: ""
      weight: 1
    - identifier: "posts"
      name: "Blog"
      url: "/posts/"
      title: ""
      weight: 2
    - identifier: "misc"
      name: "Misc"
      url: "/categories/misc/"
      title: ""
      weight: 3
    - identifier: "sobre-mi"
      name: "Sobre mí"
      url: "/sobre-mi/"
      title: ""
      weight: 4

# Markup related configuration in Hugo.
markup:
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  highlight:
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses: false

ignoreFiles:
  - .gitmodules
  - .gitignore